---
kind: pipeline
name: edge-x86

platform:
  os: linux
  arch: amd64

steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: alpinelinux/alpine-drone-ci
      tags: edge-x86
      dockerfile: dockerfiles/edge/x86/Dockerfile

---
kind: pipeline
name: v3.9-x86

platform:
  os: linux
  arch: amd64

steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: alpinelinux/alpine-drone-ci
      tags: v3.9-x86
      dockerfile: dockerfiles/v3.9/x86/Dockerfile

---
kind: pipeline
name: edge-x86_64

platform:
  os: linux
  arch: amd64

steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: alpinelinux/alpine-drone-ci
      tags: edge-x86_64
      dockerfile: dockerfiles/edge/x86_64/Dockerfile

---
kind: pipeline
name: v3.9-x86_64

platform:
  os: linux
  arch: amd64

steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: alpinelinux/alpine-drone-ci
      tags: v3.9-x86_64
      dockerfile: dockerfiles/v3.9/x86_64/Dockerfile

---
kind: pipeline
name: edge-aarch64

platform:
  os: linux
  arch: arm64

steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: alpinelinux/alpine-drone-ci
      tags: edge-aarch64
      dockerfile: dockerfiles/edge/aarch64/Dockerfile

---
kind: pipeline
name: v3.9-aarch64

platform:
  os: linux
  arch: arm64

steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: alpinelinux/alpine-drone-ci
      tags: v3.9-aarch64
      dockerfile: dockerfiles/v3.9/aarch64/Dockerfile

---
kind: pipeline
name: edge-armhf

platform:
  os: linux
  arch: arm

steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: alpinelinux/alpine-drone-ci
      tags: edge-armhf
      dockerfile: dockerfiles/edge/armhf/Dockerfile

---
kind: pipeline
name: v3.9-armhf

platform:
  os: linux
  arch: arm

steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: alpinelinux/alpine-drone-ci
      tags: v3.9-armhf
      dockerfile: dockerfiles/v3.9/armhf/Dockerfile

---
kind: pipeline
name: edge-armv7

platform:
  os: linux
  arch: arm

steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: alpinelinux/alpine-drone-ci
      tags: edge-armv7
      dockerfile: dockerfiles/edge/armv7/Dockerfile

---
kind: pipeline
name: v3.9-armv7

platform:
  os: linux
  arch: arm

steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: alpinelinux/alpine-drone-ci
      tags: v3.9-armv7
      dockerfile: dockerfiles/v3.9/armv7/Dockerfile

